apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CI verification workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  verify:
    if: ${{ cloudbees.scm.branch != 'main' }}
    outputs:
      CODE_COVERAGE: ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
      - name: runs test
        id: RunUnitTest
        kind: test
        uses: docker://golang:1.23
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init
          go test -v -timeout 15m -coverprofile=coverage.out ./... | tee ./test.log
          cat ./test.log | go-junit-report >./test.xml
          cat coverage.out >> $CLOUDBEES_OUTPUTS/CODE_COVERAGE
          go build

      - name: Print test results
        uses: docker://golang:1.20.3-alpine3.17
        run: |
          find .

      - name: Publish test results
        if: ${{ always() }}
        uses: cloudbees-io/publish-test-results@v1
        with:
          folder-name: ${{ cloudbees.workspace }}/test.xml
          test-type: go
        
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test code coverage
            ${{ steps.RunUnitTest.outputs.CODE_COVERAGE }}
          format: MARKDOWN
  
